[connection]
odbc_driver = "ODBC Driver 17 for SQL Server"
server_instancename = '.\COMPAC17'
database = "COMSP_CAYCO"
username = "sa"
use_trusted_connection = false
password = "CONTPAQi1."
table = "arkikAnalizeReports"

[config]
ruta_absoluta = true
ruta_reportes_nuevos = 'C:\Compac\ComercialSP\Reportes'
ruta_reportes_procesados = 'C:\Compac\ComercialSP\Reportes\procesados'