[app]
config_mode = false

[connection]
odbc_driver = "ODBC Driver 17 for SQL Server"
server_instancename = '.\COMPAC17'
database = "master"
username = "sa"
use_trusted_connection = false
password = "Sistemas1."
table = "arkikAnalizeReports"

[config]
ruta_reportes_nuevos = 'C:\Compac\ComercialSP\Reportes'
ruta_reportes_procesados = 'C:\Compac\ComercialSP\Reportes\procesados'